version: "3.9"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"   # Blob
      - "10001:10001"   # Queue
      - "10002:10002"   # Table
    volumes:
      - azurite_data:/data
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 -l /data"

  traffic_ingestor:
    build:
      context: ./traffic_ingestor
      dockerfile: Dockerfile
    container_name: traffic_ingestor
    environment:
      - STORAGE_CONNECTION_STRING=UseDevelopmentStorage=true
      - OUTPUT_CONTAINER=visualizations
    depends_on:
      - azurite
    ports:
      - "7072:80"   # function host for ingestor

  traffic_refresher:
    build:
      context: ./traffic_refresher
      dockerfile: Dockerfile
    container_name: traffic_refresher
    environment:
      - STORAGE_CONNECTION_STRING=UseDevelopmentStorage=true
      - OUTPUT_CONTAINER=visualizations
    depends_on:
      - azurite
    ports:
      - "7073:80"   # function host for refresher

volumes:
  azurite_data:
