name: Run Function Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      STORAGE_CONNECTION_STRING: "UseDevelopmentStorage=true"
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
      PYTHONPATH: "."
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r traffic_ingestor/requirements.txt
          pip install -r traffic_refresher/requirements.txt
      - name: Run tests
        run: pytest -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Azure
        run: echo "Deploying only because tests passed!"
