name: Run Azure Function Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Dummy values so tests don’t crash on missing env vars
      STORAGE_CONNECTION_STRING: "UseDevelopmentStorage=true"
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
      PYTHONPATH: "."
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f traffic_ingestor/requirements.txt ]; then pip install -r traffic_ingestor/requirements.txt; fi
          if [ -f traffic_refresher/requirements.txt ]; then pip install -r traffic_refresher/requirements.txt; fi

      - name: Run tests
        run: |
          pytest -v
